title: Huellas de Amor
description: Plataforma web de adopción y apadrinamiento de mascotas
theme: minima
baseurl: "/huellas_de_amor"
url: "https://kelly-mastrodomenico.github.io"
author: Kelly Rodríguez Mastrodomenico
